{% set version = "1.2" %}

package:
  name: t_rax
  version: {{ version }}

source:
  ## git_rev: {{ version }}
  git_url: https://github.com/erangre/T-rax.git
  git_tag: 13IDD_Raman_C2

build:
  number: 7
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.10
    - scipy>=0.17
    - six>=1.10
    - h5py
    - matplotlib
    - qtpy
    - pyqtgraph
    - lmfit
    - pyshortcuts

  run:
    - python
    - setuptools
    - numpy>=1.10
    - scipy>=0.17
    - six>=1.10
    - h5py
    - matplotlib
    - qtpy
    - pyqtgraph
    - lmfit
    - pyshortcuts

about:
  home: http://github.com/erangre/T-Rax
  license: GPLv3
  summary: >
      View Raman and Spectrscopic data

