# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda
    - export PYTHONPATH=$PWD/source:$PYTHONPATH

    #start x-server
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy dateutil nose pyqt
    - pip install lmfit coverage pyqtgraph
    - git clone https://github.com/luindil/pyqtgraph
    - cd pyqtgraph
    - python setup.py install

script:
    - cd source/test
    - nosetests --with-coverage --cover-package=controller,model,view