# This is a basic workflow to help you get started with Actions

name: CD_LINUX

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Use Python Dependency Cache
      id: pip-cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('T-Rax.spec') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Apt Dependencies
      run: sudo apt-get install gfortran libgfortran3 libxkbcommon-x11-0

    - name: Install Pip Dependencies
      run: |
        pip install scipy python-dateutil pytest pyqt5 h5py qtpy lmfit mock pyshortcuts pyinstaller
        pip install --pre pyqtgraph

    - name: Run T-rax from source to test and create version file
      run: xvfb-run run_t_rax.py test
        
    - name: Run PyInstaller
      run: pyinstaller T-Rax.spec

#    - name: Clean Up Executable Folder
#      run: |
#        cd dist/T-Rax*
#        rm libQt5Quick.so.5 libQt5Qml.so.5 libQt5Network.so.5 libcrypto.so.1.1 libsqlite3.so.0
#        rm -r imageio matplotlib mpl-data

    - name: Run T-Rax executable
      run: |
        cd dist/T-Rax*
        xvfb-run ./T-Rax test

    - name: Compress Executable
      run: |
        cd dist
        export folderName=$(ls | grep T-Rax)
        tar -zcvf $folderName.tar.gz $folderName
        du -sh $folderName.tar.gz

    - name: Upload Compressed App to Dropbox
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: |
        pip install dropbox
        cd dist
        export compressedFile=$(ls | grep .tar.gz)
        export targetFile='/develop/linux/'$compressedFile
        python ../scripts/dropbox_upload.py $compressedFile $targetFile
